#**Actividad 6: Regresi√≥n no lineal**
##Daniel Cruz Arciniega - A01701370

## 1. Cargar el dataframe y analizarlo

In [ ]:
import pandas as pd
import seaborn as sns

# Cargar el archivo CSV
df = pd.read_csv("/content/cuentas_credicel.csv", encoding="latin1")
df.head()

<ipython-input-9-fe330fb576ee>:4: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/cuentas_credicel.csv", encoding="latin1")

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_eng,limite_credito,semana_actual,cp_cliente,edad_cliente,cd_cliente,edo_cliente,cd_venta,edo_venta,curp
0,3,HDNAWQ3A,30,12/11/21 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,40.02,5000,26,NaN,23.0,0,0,Tantoyuca,Veracruz,AEVM980413MVZNDR02
1,4,M418YNR4,33,12/11/21 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,35.01,6000,13,NaN,60.0,PUEBLA,PUE.,Heroica Puebla de Zaragoza,Puebla,ZALC610119MPLPRR07
2,5,SZ7V3NZT,37,13/11/21 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,25.01,0,74,NaN,58.0,TANTOYUCA,VER.,0,0,0
3,6,9I08UIQZ,38,13/11/21 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,25.01,7000,13,NaN,42.0,AMXTLAN PUE,NaN,Zacatlan,Puebla,SAMJ790115MPLNRS02
4,7,JMF4LKYU,44,13/11/21 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,25.01,7000,74,NaN,33.0,TANTOYUCA,VER.,Tantoyuca,Veracruz,TEHF880707HVZRRR07

In [ ]:
df.dtypes

folio                   int64
tag                    object
folio_solicitud         int64
fecha                  object
marca                  object
modelo                 object
plazo                  object
precio                float64
enganche              float64
descuento             float64
semana                  int64
monto_financiado      float64
costo_total             int64
monto_accesorios      float64
agente_venta           object
dis_venta              object
status                  int64
fraude                  int64
empresa                object
inversion               int64
pagos_realizados        int64
reautorizacion          int64
fecha_ultimo_pago      object
fecha_pago_proximo     object
status_cuenta          object
puntos                  int64
riesgo                float64
score_buro              int64
razones_buro           object
porc_eng              float64
limite_credito         object
semana_actual           int64
cp_cliente             object
edad_cliente          float64
cd_cliente             object
edo_cliente            object
cd_venta               object
edo_venta              object
curp                   object
dtype: object

In [ ]:
df['limite_credito'] = df['limite_credito'].str.extract('(\d+\.\d+|\d+)').astype(float)

In [ ]:
numeric = df.select_dtypes(include=['float64', 'int64']).columns
df = df[numeric]

In [ ]:
sns.pairplot(df)

NameError: ignored

##2. Valores nulos

In [ ]:
cols = [
    'precio',
    'enganche',
    'descuento',
    'monto_financiado',
    'costo_total',
    'monto_accesorios',
    'status',
    'fraude',
    'inversion',
    'pagos_realizados',
    'reautorizacion',
    'puntos',
    'edad_cliente',
    'riesgo',
    'score_buro',
    'porc_eng',
    'limite_credito'
]

for col in cols:
  median_val = df[col].median()
  df[col] = df[col].fillna(median_val)

df.isna().sum()

folio               0
folio_solicitud     0
precio              0
enganche            0
descuento           0
semana              0
monto_financiado    0
costo_total         0
monto_accesorios    0
status              0
fraude              0
inversion           0
pagos_realizados    0
reautorizacion      0
puntos              0
riesgo              0
score_buro          0
porc_eng            0
limite_credito      0
semana_actual       0
edad_cliente        0
dtype: int64

## 3. Outliers

In [ ]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5128 entries, 7243 to 22732
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   folio             5128 non-null   int64
 1   folio_solicitud   5128 non-null   int64
 2   precio            5128 non-null   float64
 3   enganche          5128 non-null   float64
 4   descuento         5128 non-null   float64
 5   semana            5128 non-null   int64
 6   monto_financiado  5128 non-null   float64
 7   costo_total       5128 non-null   int64
 8   monto_accesorios  5128 non-null   float64
 9   status            5128 non-null   int64
 10  fraude            5128 non-null   int64
 11  inversion         5128 non-null   int64
 12  pagos_realizados  5128 non-null   int64
 13  reautorizacion    5128 non-null   int64
 14  puntos            5128 non-null   int64
 15  riesgo            5128 non-null   float64
 16  score_buro        5128 non-null   int64
 17  porc_eng          5128 non-null   float64
 18  limite_credito    5128 non-null   float64
 19  semana_actual     5128 non-null   int64
 20  edad_cliente      5128 non-null   float64
dtypes: float64(9), int64(12)
memory usage: 881.4 KB